---
- hosts: myWebServers
  become: yes
  tasks:
  - name: install java on ububtu node1
    apt: 
      name: "{{mywebpackage}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: install java on redhat
    yum:
     name: "{{mywebredhat}}"
     state: present
    when: ansible_os_family=="redhat"


